<?xml version="1.0"?>0
0
0<!DOCTYPE bookstore [

<!ELEMENT bookstore (book+)>
<!ELEMENT book (title,author,price)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>

]>

<bookstore>

    <book>
        <title>Java Programming</title>
        <author>James Gosling</author>
        <price>500</price>
    </book>

    <book>
        <title>Python Basics</title>
        <author>Guido Van Rossum</author>
        <price>450</price>
    </book>

    <book>
        <title>Web Development</title>
        <author>John Smith</author>
        <price>550</price>
    </book>

    <book>
        <title>Database Systems</title>
        <author>Korth</author>
        <price>600</price>
    </book>

    <book>
        <title>Data Structures</title>
        <author>Mark Allen</author>
        <price>520</price>
    </book>

</bookstore>
